import { useState } from "react";
import { Link } from "react-router-dom";
import { Activity } from "lucide-react";
import { getAuthHeaders } from "../lib/supabase";
import { Button } from "../components/ui/Button";

type TableProbe = { table: string; ok: boolean; count: number; latencyMs: number; error?: string };
type Result = { ready: boolean; checkedAt: string; tables: TableProbe[] };
export function OperationsReadiness() {
  const [result, setResult] = useState<Result | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const check = async () => { setLoading(true); setError(""); try { const response = await fetch("/api/operations/readiness", { headers: await getAuthHeaders() }); const body = await response.json(); if (!response.ok || !body.ok) throw new Error(body.error ?? "Không kiểm tra được trạng thái hệ thống."); setResult(body); } catch (caught) { setError(caught instanceof Error ? caught.message : "Không kiểm tra được trạng thái hệ thống."); } finally { setLoading(false); } };
  return <div className="mobile-mockup-page flex h-full flex-col overflow-hidden bg-zinc-50"><div className="flex shrink-0 flex-col gap-3 border-b border-zinc-200 bg-white px-4 py-4 sm:flex-row sm:items-center sm:justify-between sm:px-6"><div><h1 className="text-xl font-bold text-zinc-900">Kiểm tra hệ thống</h1><p className="mt-1 text-sm text-zinc-500">Đối chiếu các bảng bắt buộc trên production.</p></div><Link to="/settings/operations" className="text-sm font-bold text-emerald-700">← Vận hành</Link></div><div className="flex-1 overflow-y-auto p-4 sm:p-6 custom-scrollbar"><div className="mx-auto max-w-[1200px]"><div className="mb-5 flex justify-end"><Button type="button" onClick={() => void check()} disabled={loading}><Activity className="mr-2 h-4 w-4" />{loading ? "Đang kiểm tra..." : "Kiểm tra ngay"}</Button></div>{error && <div className="mb-4 rounded-[var(--radius-control)] border border-red-100 bg-red-50 p-3 text-sm text-red-700">{error}</div>}{!result && !loading && <div className="rounded-[var(--radius-card)] border border-zinc-200 bg-white p-10 text-center text-sm text-zinc-500">Bấm Kiểm tra ngay để đối chiếu migration và bảng production.</div>}{result && <section className="rounded-[var(--radius-card)] border border-zinc-200 bg-white overflow-hidden"><div className="border-b border-zinc-100 p-4"><div className={`text-lg font-bold ${result.ready ? "text-emerald-700" : "text-red-700"}`}>{result.ready ? "Hệ thống sẵn sàng" : "Phát hiện bảng thiếu hoặc lỗi"}</div><div className="mt-1 text-sm text-zinc-500">Lần kiểm tra: {new Date(result.checkedAt).toLocaleString("vi-VN")}</div></div><div className="overflow-x-auto"><table className="min-w-[720px] w-full text-sm"><thead className="bg-zinc-50 text-left text-xs uppercase tracking-wider text-zinc-500"><tr><th className="px-4 py-3">Bảng</th><th className="px-4 py-3">Trạng thái</th><th className="px-4 py-3 text-right">Dòng</th><th className="px-4 py-3 text-right">ms</th><th className="px-4 py-3">Lỗi</th></tr></thead><tbody className="divide-y divide-zinc-100">{result.tables.map((table) => <tr key={table.table}><td className="px-4 py-3 font-bold">{table.table}</td><td className="px-4 py-3"><span className={`rounded-full px-2 py-1 text-xs font-bold ${table.ok ? "bg-emerald-50 text-emerald-700" : "bg-red-50 text-red-700"}`}>{table.ok ? "OK" : "Lỗi"}</span></td><td className="px-4 py-3 text-right">{table.count.toLocaleString("vi-VN")}</td><td className="px-4 py-3 text-right text-zinc-500">{table.latencyMs}</td><td className="px-4 py-3 text-red-600">{table.error ?? ""}</td></tr>)}</tbody></table></div></section>}</div></div></div>;
}
